CFLAGS = -O
CC = g++

transportesPesados: ejercicio_3.o
	$(CC) $(CLAGS) -o transportesPesados ejercicio_3.o

ejercicio-3/transportesPesados: ejercicio_3
	$(CC) $(CLAGS) -c ejercicio_3.cpp


clean:
	rm -f core *.o
